package pojos;
// Generated Aug 23, 2019 4:37:58 PM by Hibernate Tools 4.3.1



/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private int idDocentes;
     private String nombres;

    public Docentes() {
    }

    public Docentes(int idDocentes, String nombres) {
       this.idDocentes = idDocentes;
       this.nombres = nombres;
    }
   
    public int getIdDocentes() {
        return this.idDocentes;
    }
    
    public void setIdDocentes(int idDocentes) {
        this.idDocentes = idDocentes;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }




}


