package pojos;
// Generated Aug 23, 2019 4:37:58 PM by Hibernate Tools 4.3.1



/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private int idEstudiantes;
     private String nombres;

    public Estudiantes() {
    }

    public Estudiantes(int idEstudiantes, String nombres) {
       this.idEstudiantes = idEstudiantes;
       this.nombres = nombres;
    }
   
    public int getIdEstudiantes() {
        return this.idEstudiantes;
    }
    
    public void setIdEstudiantes(int idEstudiantes) {
        this.idEstudiantes = idEstudiantes;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Override
    public String toString(){
        return getIdEstudiantes() + " " + getNombres();
    }
}